### ISSUE TITLE
can you structure your code to use go mod ?

### ISSUE THREAD

**Issue by atakanyenel** [odddollar/Leafscript#1]
Hello,

I came across this in Reddit. The project is nice, but the requirements.txt files really surprised me. That's how python package management works. 

Can you put your leafscript/main.go in the root directory and manage your dependencies through go.mod ? 
Advantages are:
- Less confusion because now you have two directories called Leafscript in the same path.
- With the new structure tools like go get can install your program easier.

You can still leave your examples file in the root, they are not go files, so they won't be compiled into your binary anyways.

Cheers and thanks for using Go !

**Comment by odddollar** [comment]
Hi

I'm newish to Go so don't know too much about package management. How do I use go.mod?
Python is the language I'm coming from so I just put the required library into a text file, as I'm not really sure of the correct way to do it.

Thanks

**Comment by atakanyenel** [comment]
Take a look at [atakanyenel/gomebrew](https://github.com/atakanyenel/gomebrew). This an repo of mine that uses the proposed structure. I dont want to do this in a PR, so that you can learn it. Here are the steps:

1) First put your main.go in the root and change your imports accordingly. That is as simple copy pasting the contents of inner Leafscript to the root. 
    - Your structure will be like:
        - main.go
        - supporting/
        - examples/
        - readme.md

2) Run the command:  `go mod init github.com/odddollar/Leafscript`. Yes, the second part is path of your repo. This will create a go.mod file.

3) Build your code with `go build`. This will create a go.sum file and add your dependency to it. This is like package-lock.json. 

4) In your main.go, you are importing supporting with './supporting'. Go uses absolute imports, so change it with 'github.com/odddollar/Leafscript/supporting'. 
    - This absolute import idea is really useful in the long run. First you know which exact packages a library uses with their paths and second if you ever need to use one of your packages in a different project, just define it in the code, and package manager will know where to find it.

- I'm around for the day, so let me know about the errors.

**Comment by odddollar** [comment]
I could not get it to work. 
Running `go build main.go` returns `supporting\domath.go:5:2: cannot find package`

**Comment by atakanyenel** [comment]
Okay, yes, before step 3, do step 4. Rename your import to have absolute import

**Comment by odddollar** [comment]
I did this and Goland had a absolute fit and said it couldn't find the specified path

**Comment by atakanyenel** [comment]
I send you a PR with the proposed changes. You can try to run it in goland
